{
 "title": "Software",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "facility",
    "label": "Facility",
    "query": "SELECT UNIQUE(facility) from \"dashboard\".\"software\""
   },
   {
    "name": "moduletype",
    "label": "Module",
    "query": "SELECT UNIQUE(module_type) FROM \"dashboard\".\"software\""
   },
   { "name": "module_new", "query": "${VAR_MODULE_NEW}" },
   {
    "name": "centre",
    "label": "Centre",
    "query": "SELECT village FROM \"dashboard\".\"software_copy1\"\nWHERE facility='$facility'"
   },
   { "name": "newmod", "query": "${VAR_NEWMOD}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "<H1><center><b>\nSoftware Status for Khurda District</b></center></H1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 0 },
   "options": {
    "content": "<H1><center><b>\nCentre Specific Software Status</b></center></H1>\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(UNIQUE(module_type)) FROM \"dashboard\".\"software\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 2 },
   "options": {
    "content": "<h3><center><b>\nModules completion percentage</b></center></h3>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 2 },
   "options": {
    "content": "<h2><center><b>\n${facility} ${centre}</b></center></h2>\n"
   }
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 10, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH first_query AS (\r\n  -- First query here\r\n  SELECT module_type, COUNT(master_data)+COUNT(configuration)+COUNT(training)+ \r\n       SUM(CASE WHEN master_data IS NULL THEN 1 ELSE 0 END) +\r\n       SUM(CASE WHEN configuration IS NULL THEN 1 ELSE 0 END) +\r\n       SUM(CASE WHEN training IS NULL THEN 1 ELSE 0 END) AS total_count\r\n  FROM \"dashboard\".\"software\"\r\n  GROUP BY module_type\r\n),\r\nsecond_query AS (\r\n  -- Second query here\r\n  SELECT module_type, SUM(total_count) AS overall_count\r\n  FROM(\r\n    SELECT m.module_type, COALESCE(s.total_count, 0) AS total_count\r\n    FROM (\r\n      SELECT DISTINCT module_type\r\n      FROM \"dashboard\".\"software\"\r\n    ) AS m\r\n    LEFT JOIN (\r\n      SELECT module_type, COUNT(master_data) AS total_count\r\n      FROM \"dashboard\".\"software\"\r\n      WHERE master_data = 'yes'\r\n      GROUP BY module_type\r\n    ) AS s ON m.module_type = s.module_type\r\n\r\n    UNION ALL\r\n\r\n    SELECT m.module_type, COALESCE(s.total_count, 0) AS total_count\r\n    FROM (\r\n      SELECT DISTINCT module_type\r\n      FROM \"dashboard\".\"software\"\r\n    ) AS m\r\n    LEFT JOIN (\r\n      SELECT module_type, COUNT(configuration) AS total_count\r\n      FROM \"dashboard\".\"software\"\r\n      WHERE configuration = 'yes'\r\n      GROUP BY module_type\r\n    ) AS s ON m.module_type = s.module_type\r\n\r\n    UNION ALL\r\n\r\n    SELECT m.module_type, COALESCE(s.total_count, 0) AS total_count\r\n    FROM (\r\n      SELECT DISTINCT module_type\r\n      FROM \"dashboard\".\"software\"\r\n    ) AS m\r\n    LEFT JOIN (\r\n      SELECT module_type, COUNT(training) AS total_count\r\n      FROM \"dashboard\".\"software\"\r\n      WHERE training = 'yes'\r\n      GROUP BY module_type\r\n    ) AS s ON m.module_type = s.module_type\r\n  )\r\n  AS combined_result\r\n  GROUP BY module_type\r\n)\r\nSELECT f.module_type, (s.overall_count / f.total_count)*100 AS division_result\r\nFROM first_query f\r\nJOIN second_query s ON f.module_type = s.module_type\r\nORDER BY f.module_type ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"dashboard\".\"software\"\r\n-- WHERE module= '$newmod'\r\nWHERE facility='$facility' AND village= '$centre'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 19 },
   "options": {
    "content": "<h2><b> <center>\r\n Overall UPHC Stats(out of 6 modules)</b></h2>"
   }
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 5, "x": 10, "y": 19 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 19 },
   "options": {
    "content": "<h2 ><b>\r\n <center>Overall CHC Stats (out of 13 modules)</b></h2>"
   }
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 5, "x": 10, "y": 20 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 21 },
   "options": {
    "content": "<h4> <center>\r\n Total Centres:"
   }
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT facility, COUNT(UNIQUE(village)) FROM \"dashboard\".\"software\"\r\nWHERE facility IN ('CHC','UPHC')\r\nGROUP BY facility\r\n"
    }
   ]
  },
  {
   "title": "Master Data Received",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(master_data) as masterdata FROM (\r\nSELECT village, master_data FROM \"dashboard\".\"software\"\r\nWHERE facility= 'UPHC'\r\nAND master_data='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Configuration done",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(configuration) as configuration FROM (\r\nSELECT village, configuration FROM \"dashboard\".\"software\"\r\nWHERE facility= 'UPHC'\r\nAND configuration='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Master Data Received",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(master_data) as masterdata FROM (\r\nSELECT village, master_data FROM \"dashboard\".\"software\"\r\nWHERE facility= 'CHC'\r\nAND master_data='yes')\r\nGROUP BY village"
    }
   ]
  },
  {
   "title": "Configuration done",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(configuration) as configuration FROM (\r\nSELECT village, configuration FROM \"dashboard\".\"software\"\r\nWHERE facility= 'CHC'\r\nAND configuration='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Training",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(training) as training FROM (\r\nSELECT village, training FROM \"dashboard\".\"software\"\r\nWHERE facility= 'UPHC'\r\nAND training='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Training ",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(training) as training FROM (\r\nSELECT village, training FROM \"dashboard\".\"software\"\r\nWHERE facility= 'CHC'\r\nAND training='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 34 },
   "options": {
    "content": "<h2><b> \r\n<center> Overall UCHC Stats (out of 13 modules) </center></b></h2>"
   }
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 5, "x": 10, "y": 34 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 34 },
   "options": {
    "content": "<h2><b> \r\n<center> <center> Overall DHH Stats (out of 19 modules) </center></b></h2>"
   }
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 5, "x": 9, "y": 35 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 36 },
   "options": {
    "content": "<h4> <center>\r\n Total Centres:"
   }
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT facility, COUNT(UNIQUE(village)) FROM \"dashboard\".\"software\"\r\nWHERE facility IN ('UCHC','DHH')\r\nGROUP BY facility\r\n"
    }
   ]
  },
  {
   "title": "Master Data Received",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(master_data) as masterdata FROM (\r\nSELECT village, master_data FROM \"dashboard\".\"software\"\r\nWHERE facility= 'UCHC'\r\nAND master_data='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Configuration done",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(configuration) as configuration FROM (\r\nSELECT village, configuration FROM \"dashboard\".\"software\"\r\nWHERE facility= 'UCHC'\r\nAND configuration='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Master Data Received",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(master_data) as masterdata FROM (\r\nSELECT village, master_data FROM \"dashboard\".\"software\"\r\nWHERE facility= 'DHH'\r\nAND master_data='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Configuration done",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(configuration) as configuration FROM (\r\nSELECT village, configuration FROM \"dashboard\".\"software\"\r\nWHERE facility= 'DHH'\r\nAND configuration='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Training",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(training) as training FROM (\r\nSELECT village, training FROM \"dashboard\".\"software\"\r\nWHERE facility= 'UCHC'\r\nAND training='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Training",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(training) as training FROM (\r\nSELECT village, training FROM \"dashboard\".\"software\"\r\nWHERE facility= 'DHH'\r\nAND training='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "<h2><b> \r\n<center> Overall PHC Stats (out of 6 modules) </center></b></h2>"
   }
  },
  {
   "title": "Total Centres:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  facility, COUNT(UNIQUE(village)) FROM \"dashboard\".\"software\"\r\nWHERE facility='PHC'\r\nGROUP BY facility\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "description": "(Out of 19 Modules)",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$A*100", "type": "math" }
   ]
  },
  {
   "title": "Master Data Received",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(master_data) as masterdata FROM (\r\nSELECT village, master_data FROM \"dashboard\".\"software\"\r\nWHERE facility= 'PHC'\r\nAND master_data='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Configuration done",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(configuration) as configuration FROM (\r\nSELECT village, configuration FROM \"dashboard\".\"software\"\r\nWHERE facility= 'PHC'\r\nAND configuration='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "title": "Training",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT village, count(training) as training FROM (\r\nSELECT village, training FROM \"dashboard\".\"software\"\r\nWHERE facility= 'PHC'\r\nAND training='yes')\r\nGROUP BY village\r\nORDER BY village"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(master_data)+ SUM(CASE WHEN master_data is null THEN 1 ELSE 0 END) AS totalMasterData\r\nFROM \"dashboard\".\"software\"\r\n\r\n"
    },
    {
     "rawSql": "SELECT COUNT(master_data) FROM \"dashboard\".\"software\" AS yes_total\r\nWHERE master_data='yes' "
    },
    { "expression": "($B/$A)", "type": "math" }
   ]
  }
 ]
}